### ISSUE TITLE
open_browser: extra fields not permitted

### ISSUE THREAD

**Issue by davidbrochart** [jupyter-server/fps#49]
## Description

FPS master breaks jupyverse with:
```
[W 2021-10-15 15:38:23 uvicorn.error] Current configuration will not reload as not all conditions are met,please refer to documentation.
[I 2021-10-15 15:38:23 fps] Loading server configuration
Traceback (most recent call last):
  File "/home/david/mambaforge/envs/jupyverse/bin/jupyverse", line 8, in <module>
    sys.exit(app())
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/david/github/davidbrochart/fps/plugins/uvicorn/fps_uvicorn/cli.py", line 138, in start
    uvicorn.run(
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/uvicorn/main.py", line 447, in run
    server.run()
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/david/mambaforge/envs/jupyverse/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/david/github/davidbrochart/fps/fps/main.py", line 3, in <module>
    app = create_app()
  File "/home/david/github/davidbrochart/fps/fps/app.py", line 279, in create_app
    _load_configurations()
  File "/home/david/github/davidbrochart/fps/fps/app.py", line 86, in _load_configurations
    Config.register("fps", FPSConfig)
  File "/home/david/github/davidbrochart/fps/fps/config.py", line 107, in register
    config = config_model.parse_obj(config_obj)
  File "pydantic/main.py", line 578, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for FPSConfig
port
  extra fields not permitted (type=value_error.extra)
```

## Reproduce

1. Clone this repository.
2. `pip install -e .`
2. `pip install -e plugins/uvicorn`
3. `pip install jupyverse`
4. `jupyverse --no-open-browser`

**Comment by davidbrochart** [comment]
In [@hbcarlos's PR](https://github.com/jupyter-server/jupyverse/pull/75/checks?check_run_id=3907195711) the error is about `open_browser`. So what's the way to specify not opening a browser now?

**Comment by adriendelsalle** [comment]
the error is https://github.com/jupyter-server/jupyverse/blob/85065394a0f1b3101974628115c6064f00792247/fps.toml#L2
